---
- name: install tomcat server
  hosts: all
  become: true
  vars:
     - tomcat_URL: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.zip
     - tomcat_Name: apache-tomcat-9.0.70
  vars_files:
     - Nexus_Vars
  tasks:
   - name: Create a Tomcat User
     user:
      name: tomcat
   - name: Create a Tomcat Group
     group:
      name: tomcat
   - name: Install OpenJDK
     apt:
      name: openjdk-11-jdk
      state: present
   - name: download & unarchive tomcat server
     unarchive:
      src: "{{tomcat_URL}}"
      dest: /opt/
      remote_src: yes
   - name: Permission for opt to Tomcat user
     file:
       path: /opt/{{tomcat_Name}}/
       owner: tomcat
       group: tomcat
       mode: 0755
   - name: Execute permission tomcat folder
     become: yes
     shell: "mv /opt/{{tomcat_Name}}/ /opt/tomcat && chmod u+x /opt/tomcat/bin/catalina.sh && chmod u+x /opt/tomcat/bin/startup.sh"

   - name: start tomcat services
     become: yes
     shell: nohup /opt/tomcat/bin/startup.sh
   - name: pull .war artifact from Artifact
     become: yes
     get_url:
       url: http://34.200.216.233:8081/repository/onlinebookstore/onlinebookstore/onlinebookstore/1.0.0/onlinebookstore-1.0.0.war
       dest: /opt/tomcat/webapps/
       url_username: siva
       url_password: "{{Nexus_Password}}"
       owner: tomcat
       group: tomcat
       mode: 0644
